### ISSUE TITLE
<ng-container /> not working

### ISSUE THREAD

**Issue by akinnez** [analogjs/analog#1137]
### Please provide the environment you discovered this bug in.
I did noticed that i was using <ng-container /> but its not working as expected

### Which area/package is the issue in?

create-analog

### Description

import {
    Component,
    OnInit,
    ViewContainerRef,
    inject,
    viewChild,
} from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
    selector: 'app-write-blog',
    standalone: true,
    imports: [],
    template: `
        <div>
            <ng-container #container></ng-container>
        </div>
    `,
})
export default class WriteBlogPageComponent implements OnInit {
    write = viewChild.required('container', { read: ViewContainerRef });

    protected activatedRoute = inject(ActivatedRoute);

    constructor() {}
    ngOnInit(): void {
        let vs = this.activatedRoute.queryParams.subscribe({
            next: (res) => {
                this.loadComponent(res['writeId']);
            },
            complete: () => {
                vs.unsubscribe();
            },
        });
    }

    async loadComponent(queryParams: string | undefined) {
        this.write()?.clear();
        if (queryParams) {
            const { EditBlogComponent } = await import(
                '../../views/blogs/edit/edit.component'
            );
            this.write()?.createComponent(EditBlogComponent);
            return;
        }
        const { CreateBlogComponent } = await import(
            '../../views/blogs/create/create.component'
        );

        this.write()?.createComponent(CreateBlogComponent);
        return;
    }
}

### Please provide the exception or error you saw

```true
C:/Users/ridhw/Desktop/analog-project/node_modules/@angular/core/fesm2022/core.mjs:3162
            throw new RuntimeError(205 /* RuntimeErrorCode.INJECTOR_ALREADY_DESTROYED */, ngDevMode && 'Injector has already been destroyed.');
                  ^

RuntimeError: NG0205: Injector has already been destroyed.
    at R3Injector.assertNotDestroyed (C:/Users/ridhw/Desktop/analog-project/node_modules/@angular/core/fesm2022/core.mjs:3162:19)
    at R3Injector.get (C:/Users/ridhw/Desktop/analog-project/node_modules/@angular/core/fesm2022/core.mjs:3049:14)
    at ChainedInjector.get (C:/Users/ridhw/Desktop/analog-project/node_modules/@angular/core/fesm2022/core.mjs:15729:36)
    at lookupTokenUsingModuleInjector (C:/Users/ridhw/Desktop/analog-project/node_modules/@angular/core/fesm2022/core.mjs:5735:39)
    at getOrCreateInjectable (C:/Users/ridhw/Desktop/analog-project/node_modules/@angular/core/fesm2022/core.mjs:5783:12)
    at NodeInjector.get (C:/Users/ridhw/Desktop/analog-project/node_modules/@angular/core/fesm2022/core.mjs:6077:16)
    at ViewContainerRef.createComponent (C:/Users/ridhw/Desktop/analog-project/node_modules/@angular/core/fesm2022/core.mjs:16263:38)
    at WriteBlogPageComponent.loadComponent (C:/Users/ridhw/Desktop/analog-project/src/app/pages/blog/write.page.ts:33:23) {
  code: 205
}
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Try with the latest release
