### ISSUE TITLE
Including {slugs} in sitemap when using blogtype (SSG)

### ISSUE THREAD

**Issue by RiddleTime** [analogjs/analog#1164]
### Please provide the environment you discovered this bug in.

https://github.com/RiddleTime/Race-Element/tree/pages

### Which area/package is the issue in?

Don't know / other

### Description

I am using the Blog type format(Content Routing) with Analog, but I wonder if it's possible to also include the generated blog pages to the sitemap. 

When enabling the sitemap option in the vite.config.ts the slug/content pages were not included in the sitemap.xml

### Please provide the exception or error you saw
No exception was given when generating the sitemap although this exception was given when hard-coding one of the news or guide slugs in the routes array:
```true
✓ built in 8.03s
Prerendering static pages...
TypeError: Failed to parse URL from guide/features
    at node:internal/deps/undici/undici:12502:13
    at _ZoneDelegate.invoke (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:365:28)
    ... 9 lines matching cause stack trace ...
    at process.processTimers (node:internal/timers:514:7) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:797:36)
      at new Request (node:internal/deps/undici/undici:4853:25)
      at fetch (node:internal/deps/undici/undici:9662:25)
      at fetch (node:internal/deps/undici/undici:12500:10)
      at value (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at ufetch (file:///C:/Users/Reinier/source/repos/Race-Element/node_modules/unenv/runtime/fetch/index.mjs:6:14)
      at localFetch (file:///C:/Users/Reinier/source/repos/Race-Element/dist/.nitro/prerender/index.mjs:948:39)
      at generateRoute (file:///C:/Users/Reinier/source/repos/Race-Element/node_modules/nitropack/dist/chunks/prerender.mjs:114:23)
      at file:///C:/Users/Reinier/source/repos/Race-Element/node_modules/nitropack/dist/chunks/prerender.mjs:236:92
      at _ZoneDelegate.invoke (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:365:28)
      at ZoneImpl.run (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:111:43)
      at C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:1192:40
      at _ZoneDelegate.invokeTask (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:398:33)
      at ZoneImpl.runTask (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:158:47)
      at drainMicroTaskQueue (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:577:35)
      at invokeTask (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:483:21)
      at ZoneTask.invoke (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:468:48)
      at data.args.<computed> [as _onTimeout] (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:2231:32)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ERR_INVALID_URL',
    input: 'guide/features'
  }
}
TypeError: Failed to parse URL from guide/features
    at node:internal/deps/undici/undici:12502:13
    at _ZoneDelegate.invoke (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:365:28)
    ... 9 lines matching cause stack trace ...
    at process.processTimers (node:internal/timers:514:7) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:797:36)
      at new Request (node:internal/deps/undici/undici:4853:25)
      at fetch (node:internal/deps/undici/undici:9662:25)
      at fetch (node:internal/deps/undici/undici:12500:10)
      at value (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at ufetch (file:///C:/Users/Reinier/source/repos/Race-Element/node_modules/unenv/runtime/fetch/index.mjs:6:14)
      at localFetch (file:///C:/Users/Reinier/source/repos/Race-Element/dist/.nitro/prerender/index.mjs:948:39)
      at generateRoute (file:///C:/Users/Reinier/source/repos/Race-Element/node_modules/nitropack/dist/chunks/prerender.mjs:114:23)
      at file:///C:/Users/Reinier/source/repos/Race-Element/node_modules/nitropack/dist/chunks/prerender.mjs:236:92
      at _ZoneDelegate.invoke (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:365:28)
      at ZoneImpl.run (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:111:43)
      at C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:1192:40
      at _ZoneDelegate.invokeTask (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:398:33)
      at ZoneImpl.runTask (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:158:47)
      at drainMicroTaskQueue (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:577:35)
      at invokeTask (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:483:21)
      at ZoneTask.invoke (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:468:48)
      at data.args.<computed> [as _onTimeout] (C:\Users\Reinier\source\repos\Race-Element\node_modules\zone.js\fesm2015\zone-node.js:2231:32)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'ERR_INVALID_URL',
    input: 'guide/features'
  }
}
Building Sitemap...
Writing sitemap at C:\Users\Reinier\source\repos\Race-Element\dist\analog\public/sitemap.xml```
```

### Other information

Original help topic in discord of Analog: https://discord.com/channels/994618831987290112/1251242804844429414

vite.config.ts at moment of writing this issue:

```/// <reference types="vitest" />

import { defineConfig } from 'vite';
import analog, { type PrerenderContentFile } from '@analogjs/platform';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  build: {
    target: ['es2020'],
  },
  resolve: {
    mainFields: ['module'],
  },
  plugins: [
    analog({
      static: true,
      prerender: {
        routes: [
          '/',
          '/setup',
          '/news',
          {
            contentDir: 'src/content/news',
            transform: (file: PrerenderContentFile) => {
              // do not include files marked as draft in frontmatter
              if (file.attributes['draft']) {
                return false;
              }
              // use the slug from frontmatter if defined, otherwise use the files basename
              const slug = file.attributes['slug'] || file.name;
              return `/news/${slug}`;
            },
          },
          '/guide',
          {
            contentDir: 'src/content/guide',
            transform: (file: PrerenderContentFile) => {
              // do not include files marked as draft in frontmatter
              if (file.attributes['draft']) {
                return false;
              }
              // use the slug from frontmatter if defined, otherwise use the files basename
              const slug = file.attributes['slug'] || file.name;
              return `/guide/${slug}`;
            },
          },
        ],
        sitemap: {
          host: 'https://race.elementfuture.com/',
        }
      },
    }),
  ],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['src/test-setup.ts'],
    include: ['**/*.spec.ts'],
    reporters: ['default'],
  },
  define: {
    'import.meta.vitest': mode !== 'production',
  },
}));
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by RiddleTime** [comment]
Solved by placing the .md (content files) in the correct folders as I specified in the vite.config.ts
Additionality in the slug components I specified the folders as well.

User mistake, my bad :D 

```typescript
  readonly post = injectContent<PostAttributes>({
    param: 'slug',
    subdirectory: 'news',
  });
```
