### ISSUE TITLE
Cannot import angular packages within monorepo setup with workspaces (npm, pnpm)

### ISSUE THREAD

**Issue by riccardoperra** [analogjs/analog#1205]
### Please provide the environment you discovered this bug in.

Tested on both stackblitz and my machine, sometimes I get some other error (always something related about the compilation) 

Simple reproduction: https://stackblitz.com/edit/github-e9p48n?file=pnpm-workspace.yaml

### Which area/package is the issue in?

vite-plugin-angular

### Description

I was planning to use Analog to build a simple documentation site for a library that I'm working on these days, but unfortunately I got some issues while running the dev server to display something :/ 

like the stackblitz I provided, I've a simple monorepo setup (for now) with 2 packages: `docs` and `my-lib-name`. 
`my-lib-name` is an angular library (generated via angular cli, but with a setup like @tanstack/angular libraries) that exports services/components/utilities.

```json
{
  "name": "my-lib-name", 
  "exports": {
      ...
   }
  "dependencies": { 
   }
}
```

The docs package import the `my-lib-name` pkg via pnpm-workspaces, so I've defined it as a dependency in the package.json

```json
{
  "name": "docs", 
  "dependencies": { 
    "my-lib-name": "workspace:*"
 }
}
```

As soon as I import something from the library, everything seems to fall apart. 

As a temporary workaround for now I'm using tsconfig paths and pointing directly to src, but it seems an approach completely wrong to me after having worked with workspaces for some time.

EDIT: with this workaround after a refresh I got this error just by calling a function into a directive

```ts
class MyDirective { 
  readonly el = injectElement();
}

function injectElement() {
  return inject(ElementRef).nativeElement
}
```

```bash
NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
    at injectInjectorOnly (/Users/riccardoperra/WebstormProjects/ariangular/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.8.1_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:1105:15)
    at ɵɵinject (/Users/riccardoperra/WebstormProjects/ariangular/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.8.1_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:1118:61)
    at Module.inject (/Users/riccardoperra/WebstormProjects/ariangular/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.8.1_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:1204:12)
    at Module.injectElement
```

EDIT 2: some other error that always appear and break the dev server

```bash
/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.8.1_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:28650
    if (tView.firstCreatePass) {
              ^

TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at providersResolver (/Users/riccardoperra/WebstormProjects/my-project/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.8.1_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:28650:15)
    at definition.providersResolver (/Users/riccardoperra/WebstormProjects/my-project/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.8.1_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:28909:20)
    at initializeDirectives (/Users/riccardoperra/WebstormProjects/my-project/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.5.7_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:12170:17)
    at resolveDirectives (/Users/riccardoperra/WebstormProjects/my-project/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.5.7_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:12144:13)
    at elementStartFirstCreatePass (/Users/riccardoperra/WebstormProjects/my-project/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.5.7_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:24309:5)
    at Module.ɵɵelementStart (/Users/riccardoperra/WebstormProjects/my-project/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.5.7_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:24345:11)
    at Basic_Template (/Users/riccardoperra/WebstormProjects/my-project/packages/docs/src/app/pages/(collapsible)/_basic.ts:17:35)
    at executeTemplate (/Users/riccardoperra/WebstormProjects/my-project/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.5.7_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:11627:9)
    at renderView (/Users/riccardoperra/WebstormProjects/my-project/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.5.7_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:12834:13)
    at renderComponent (/Users/riccardoperra/WebstormProjects/my-project/node_modules/.pnpm/@angular+core@18.0.6_rxjs@7.5.7_zone.js@0.14.7/node_modules/@angular/core/fesm2022/core.mjs:12780:5)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Try with the latest release as we've updated detection of packages needed SSR transform
