### ISSUE TITLE
need to kill cli each time creating a new page or folder

### ISSUE THREAD

**Issue by mhamri** [analogjs/analog#1345]
### Please provide the environment you discovered this bug in.

windows/wsl

### Which area/package is the issue in?

vite-plugin-angular

### Description

each time adding a new page or layout I have to kill the cli and run the npm start again

### Please provide the exception or error you saw

```true
ERROR RuntimeError: NG04002: Cannot match any routes. URL Segment: 'products'
    at Recognizer.noMatchError (E:/hustling/thetutr/t1/frontend-ng/node_modules/.pnpm/@angular+router@18.2.3_@angular+common@18.2.3_@angular+core@18.2.3_rxjs@7.8.1_zone.js@0.14.10_fvhtnhzbov4bwdsdhvj2pkw3ji/node_modules/@angular/router/fesm2022/router.mjs:3781:16)
    at eval (E:/hustling/thetutr/t1/frontend-ng/node_modules/.pnpm/@angular+router@18.2.3_@angular+common@18.2.3_@angular+core@18.2.3_rxjs@7.8.1_zone.js@0.14.10_fvhtnhzbov4bwdsdhvj2pkw3ji/node_modules/@angular/router/fesm2022/router.mjs:3811:28)
    at E:\hustling\thetutr\t1\frontend-ng\node_modules\.pnpm\rxjs@7.8.1\node_modules\rxjs\dist\cjs\internal\operators\catchError.js:13:51
    at OperatorSubscriber._this._error (E:\hustling\thetutr\t1\frontend-ng\node_modules\.pnpm\rxjs@7.8.1\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:43:21)
    at Subscriber.error (E:\hustling\thetutr\t1\frontend-ng\node_modules\.pnpm\rxjs@7.8.1\node_modules\rxjs\dist\cjs\internal\Subscriber.js:60:18)
    at Subscriber._error (E:\hustling\thetutr\t1\frontend-ng\node_modules\.pnpm\rxjs@7.8.1\node_modules\rxjs\dist\cjs\internal\Subscriber.js:84:30)
    at Subscriber.error (E:\hustling\thetutr\t1\frontend-ng\node_modules\.pnpm\rxjs@7.8.1\node_modules\rxjs\dist\cjs\internal\Subscriber.js:60:18)
    at Subscriber._error (E:\hustling\thetutr\t1\frontend-ng\node_modules\.pnpm\rxjs@7.8.1\node_modules\rxjs\dist\cjs\internal\Subscriber.js:84:30)
    at Subscriber.error (E:\hustling\thetutr\t1\frontend-ng\node_modules\.pnpm\rxjs@7.8.1\node_modules\rxjs\dist\cjs\internal\Subscriber.js:60:18)
    at Subscriber._error (E:\hustling\thetutr\t1\frontend-ng\node_modules\.pnpm\rxjs@7.8.1\node_modules\rxjs\dist\cjs\internal\Subscriber.js:84:30) {
  code: 4002
}
```

### Other information

![image](https://github.com/user-attachments/assets/aaefbde9-b24d-4669-87ce-7cf4e4331c77)

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Try again with the latest `1.9.0` release, as this should be resolved on Windows.
