### ISSUE TITLE
bug: Nx 15.4.x requires a project.json to work correctly

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#188]
### Please provide the environment you discovered this bug in.

https://analogjs.org/new

### Which area/package is the issue in?

Don't know / Other

### Description

Prior to Nx 15.4.x, the @nrwl/vite package could be used in as an Angular CLI builder without any additional dependencies. In 15.4 the app no longer runs and displays an error

https://stackblitz.com/edit/github-ba5rvt?file=package.json&preset=node

### Please provide the exception or error you saw

```true
$ ng serve
An unhandled exception occurred: Cannot read properties of undefined (reading 'data')
See "/tmp/ng-rfo1eP/angular-errors.log" for further details.

~/projects/github-ba5rvt 5s
❯ cat /tmp/ng-rfo1eP/angular-errors.log
[error] TypeError: Cannot read properties of undefined (reading 'data')
    at readTargetOptions (file:///home/projects/github-ba5rvt/node_modules/@nrwl/devkit/src/executors/read-target-options.js:13:70)
    at getBuildTargetOptions (file:///home/projects/github-ba5rvt/node_modules/@nrwl/vite/src/utils/options-utils.js:70:42)
    at viteDevServerExecutor (file:///home/projects/github-ba5rvt/node_modules/@nrwl/vite/src/executors/dev-server/dev-server.impl.js:11:80)
    at viteDevServerExecutor.next (<anonymous>)
    at recurse (file:///home/projects/github-ba5rvt/node_modules/@nrwl/devkit/src/utils/convert-nx-executor.js:55:26)
    at eval (file:///home/projects/github-ba5rvt/node_modules/@nrwl/devkit/src/utils/convert-nx-executor.js:72:17)
```

### Other information

Running `npx nx init` to setup Nx, then running `ng serve` works 

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Fixed in Nx 15.4.3
