### ISSUE TITLE
An example from documentation doesn't work 

### ISSUE THREAD

**Issue by OgiSss** [analogjs/analog#342]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/github/analogjs/analog/tree/stackblitz/packages/create-analog/template-angular-v15?file=vite.config.ts&preset=node

### Which area/package is the issue in?

Docs

### Description

Hi, 

An example in docs doesn't work. Go to https://analogjs.org/ click on button "Open in Stackblitz".

https://stackblitz.com/github/analogjs/analog/tree/stackblitz/packages/create-analog/template-angular-v15?file=vite.config.ts&preset=node

### Please provide the exception or error you saw

```true
failed to load config from /home/projects/wmaigwzlv.github/vite.config.ts
error when starting dev server:
Error: Cannot find module '@angular-devkit/build-angular/src/builders/browser-esbuild/angular/aot-compilation'
Require stack:
- /home/projects/wmaigwzlv.github/node_modules/@analogjs/vite-plugin-angular/src/lib/compiler-plugin.js
- /home/projects/wmaigwzlv.github/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js
- /home/projects/wmaigwzlv.github/node_modules/@analogjs/vite-plugin-angular/src/index.js
- /home/projects/wmaigwzlv.github/node_modules/@analogjs/platform/src/lib/platform-plugin.js
- /home/projects/wmaigwzlv.github/node_modules/@analogjs/platform/src/index.js
- /home/projects/wmaigwzlv.github/vite.config.ts
- /home/projects/wmaigwzlv.github/node_modules/vite/dist/node/chunks/dep-79892de8.js
    at Module._resolveFilename (https://wmaigwzlvgithub-yyza.w-credentialless.staticblitz.com/blitz.9926f97d.js:35:242305)
    at Module._load (https://wmaigwzlvgithub-yyza.w-credentialless.staticblitz.com/blitz.9926f97d.js:35:239836)
    at Module.require (https://wmaigwzlvgithub-yyza.w-credentialless.staticblitz.com/blitz.9926f97d.js:35:243084)
    at i (https://wmaigwzlvgithub-yyza.w-credentialless.staticblitz.com/blitz.9926f97d.js:35:480348)
    at _0x39573c (https://wmaigwzlvgithub-yyza.w-credentialless.staticblitz.com/blitz.9926f97d.js:44:143771)
    at Object.eval (file:///home/projects/wmaigwzlv.github/node_modules/@analogjs/vite-plugin-angular/src/lib/compiler-plugin.js:18:27)
    at Object.function (https://wmaigwzlvgithub-yyza.w-credentialless.staticblitz.com/blitz.9926f97d.js:44:144540)
    at Module._compile (https://wmaigwzlvgithub-yyza.w-credentialless.staticblitz.com/blitz.9926f97d.js:35:244076)
    at Module._extensions..js (https://wmaigwzlvgithub-yyza.w-credentialless.staticblitz.com/blitz.9926f97d.js:35:244741)
    at _require.extensions.<computed> [as .js] (file://file:///home/projects/wmaigwzlv.github/node_modules/vite/dist/node/chunks/dep-79892de8.js:64038:17)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This has been fixed on the `stackblitz` branch, but you can fix your fork by adding `@analogjs/vite-plugin-angular@0.2.0-alpha.22` to the `package.json`

Here's a working example

https://stackblitz.com/edit/github-h5wshl?file=package.json&preset=node
