### ISSUE TITLE
Vite plugin angular - Cannot read properties of undefined (reading 'flags')

### ISSUE THREAD

**Issue by sand4rt** [analogjs/analog#346]
### Please provide the environment you discovered this bug in.

Code in which the error occurs: https://github.com/sand4rt/playwright-ct-angular/pull/1

### Which area/package is the issue in?

vite-plugin-angular

### Description

Hey @brandonroberts, tried integrating `@analogjs/vite-plugin-angular` into Playwright Angular component testing based on the example project you made: https://github.com/brandonroberts/analog-playwright-component-tests. I get the error below but i can't figure out why.. Do you know what's wrong here?

### Please provide the exception or error you saw

```true
[@analogjs/vite-plugin-angular] Cannot read properties of undefined (reading 'flags
TypeError: Cannot read properties of undefined (reading 'flags')

    at checkUnreachable (/playwright-ct-angular/node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib/typescript.js:48693:31)
    at bindChildren (/playwright-ct-angular/node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib/typescript.js:46237:17)
    at bind (/playwright-ct-angular/node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib/typescript.js:47772:21)
    at bindSourceFile (/playwright-ct-angular/node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib/typescript.js:45777:17)
    at Object.bindSourceFile (/playwright-ct-angular/node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib/typescript.js:45713:9)
    at initializeTypeChecker (/playwright-ct-angular/node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib/typescript.js:89424:20)
    at Object.createTypeChecker (/playwright-ct-angular/node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib/typescript.js:49942:9)
    at Object.getTypeChecker (/playwright-ct-angular/node_modules/.pnpm/typescript@4.9.5/node_modules/typescript/lib/typescript.js:120222:53)
    at NgCompiler (/playwright-ct-angular/node_modules/packages/compiler-cli/src/ngtsc/core/src/compiler.ts:344:38)
    at Function.fromTicket (/playwright-ct-angular/node_modules/packages/compiler-cli/src/ngtsc/core/src/compiler.ts:280:16)
    at NgtscProgram (/playwright-ct-angular/node_modules/packages/compiler-cli/src/ngtsc/program.ts:113:32)
    at playwright-ct-angular/node_modules/.pnpm/@analogjs+vite-plugin-angular@0.2.0-beta.1_@angular-devkit+build-angular@16.0.0-rc.0/packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts:418:42
    at playwright-ct-angular/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:167:75
    at Object.__awaiter (/playwright-ct-angular/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:163:16)
    at buildAndAnalyze (/playwright-ct-angular/node_modules/.pnpm/@analogjs+vite-plugin-angular@0.2.0-beta.1_@angular-devkit+build-angular@16.0.0-rc.0/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js:348:24)
    at Object.<anonymous> (/playwright-ct-angular/node_modules/.pnpm/@analogjs+vite-plugin-angular@0.2.0-beta.1_@angular-devkit+build-angular@16.0.0-rc.0/packages/vite-plugin-angular/src/lib/angular-vite-plugin.ts:147:15)
    at playwright-ct-angular/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:167:75
    at Object.__awaiter (/playwright-ct-angular/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:163:16)
    at Object.buildStart (/playwright-ct-angular/node_modules/.pnpm/@analogjs+vite-plugin-angular@0.2.0-beta.1_@angular-devkit+build-angular@16.0.0-rc.0/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js:99:32)
    at playwright-ct-angular/node_modules/.pnpm/rollup@3.17.3/node_modules/rollup/dist/es/shared/node-entry.js:24171:40
    at PluginDriver.hookParallel (/playwright-ct-angular/node_modules/.pnpm/rollup@3.17.3/node_modules/rollup/dist/es/shared/node-entry.js:24099:9)
    at playwright-ct-angular/node_modules/.pnpm/rollup@3.17.3/node_modules/rollup/dist/es/shared/node-entry.js:25374:13
    at catchUnfinishedHookActions (/playwright-ct-angular/node_modules/.pnpm/rollup@3.17.3/node_modules/rollup/dist/es/shared/node-entry.js:24534:20)
    at rollupInternal (/playwright-ct-angular/node_modules/.pnpm/rollup@3.17.3/node_modules/rollup/dist/es/shared/node-entry.js:25371:5)
    at Module.build (/playwright-ct-angular/node_modules/.pnpm/vite@4.1.4_@types+node@18.14.2_less@4.1.3/node_modules/vite/dist/node/chunks/dep-ca21228b.js:44664:18)
```

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by sand4rt** [comment]
Updated TypeScript to v4.9.0 and it works now.
