### ISSUE TITLE
SSR Server crash when navigating to an unknown route

### ISSUE THREAD

**Issue by zawasp** [analogjs/analog#405]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/edit/github-qpprba

### Which area/package is the issue in?

router

### Description

With the default create-analog template, when navigating to an unknown route, the app crashes, unless you provide a catch-all route.

### Please provide the exception or error you saw

```true
`
RuntimeError: NG04002: Cannot match any routes. URL Segment: 'asdsad'
    at Recognizer.noMatchError (/home/projects/github-qpprba/node_modules/@angular/router/fesm2022/router.mjs:3664:16)
    at eval (/home/projects/github-qpprba/node_modules/@angular/router/fesm2022/router.mjs:3679:28)
    at eval (file:///home/projects/github-qpprba/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51)
    at OperatorSubscriber._this._error (file:///home/projects/github-qpprba/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
    at Subscriber.error (file:///home/projects/github-qpprba/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (file:///home/projects/github-qpprba/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (file:///home/projects/github-qpprba/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (file:///home/projects/github-qpprba/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (file:///home/projects/github-qpprba/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (file:///home/projects/github-qpprba/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30) {
  code: 4002
}
`
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This doesn't seem to be an issue in the latest release. Re-open if so

**Comment by zawasp** [comment]
@brandonroberts I still get an error when calling API routes:
*STR*
- create analog project using pnpm (using beta 19)
- build
- run `node dist/analog/server/index.mjs`
- navigate to http://localhost:3000/api/v1/hello

Expected:
no errors in console
Actual:
```
Listening http://[::]:3000
ERROR Error: Uncaught (in promise): Error: NG04002
Error: NG04002
    at Recognizer.noMatchError (file:///home/mrila/work/playground/analogcf/dist/analog/server/chunks/main.server.mjs:35531:12)
    at file:///home/mrila/work/playground/analogcf/dist/analog/server/chunks/main.server.mjs:35542:20
    at /home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51
    at OperatorSubscriber._this._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
    at Subscriber.error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at resolvePromise (/home/mrila/work/playground/analogcf/dist/analog/server/node_modules/zone.js/bundles/zone-node.umd.js:1179:35)
    at resolvePromise (/home/mrila/work/playground/analogcf/dist/analog/server/node_modules/zone.js/bundles/zone-node.umd.js:1133:21)
    at /home/mrila/work/playground/analogcf/dist/analog/server/node_modules/zone.js/bundles/zone-node.umd.js:1246:21
    at _ZoneDelegate.invokeTask (/home/mrila/work/playground/analogcf/dist/analog/server/node_modules/zone.js/bundles/zone-node.umd.js:446:35)
    at Object.onInvokeTask (file:///home/mrila/work/playground/analogcf/dist/analog/server/chunks/main.server.mjs:7523:25)
    at _ZoneDelegate.invokeTask (/home/mrila/work/playground/analogcf/dist/analog/server/node_modules/zone.js/bundles/zone-node.umd.js:445:64)
    at Zone.runTask (/home/mrila/work/playground/analogcf/dist/analog/server/node_modules/zone.js/bundles/zone-node.umd.js:211:51)
    at drainMicroTaskQueue (/home/mrila/work/playground/analogcf/dist/analog/server/node_modules/zone.js/bundles/zone-node.umd.js:635:39) {
  rejection: RuntimeError: NG04002
      at Recognizer.noMatchError (file:///home/mrila/work/playground/analogcf/dist/analog/server/chunks/main.server.mjs:35531:12)
      at file:///home/mrila/work/playground/analogcf/dist/analog/server/chunks/main.server.mjs:35542:20
      at /home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51
      at OperatorSubscriber._this._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
      at Subscriber.error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
      at Subscriber.error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
      at Subscriber.error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30) {
    code: 4002
  },
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: RuntimeError: NG04002
        at Recognizer.noMatchError (file:///home/mrila/work/playground/analogcf/dist/analog/server/chunks/main.server.mjs:35531:12)
        at file:///home/mrila/work/playground/analogcf/dist/analog/server/chunks/main.server.mjs:35542:20
        at /home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51
        at OperatorSubscriber._this._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
        at Subscriber.error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
        at Subscriber._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
        at Subscriber.error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
        at Subscriber._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
        at Subscriber.error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
        at Subscriber._error (/home/mrila/work/playground/analogcf/node_modules/.pnpm/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30) {
      code: 4002
    }
  },
  zone: <ref *1> Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [_ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: <ref *2> _ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular *1],
      _parentDelegate: [_ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [_ZoneDelegate],
      _invokeCurrZone: [Circular *1],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [_ZoneDelegate],
      _handleErrorCurrZone: [Circular *1],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [_ZoneDelegate],
      _scheduleTaskCurrZone: [Circular *1],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [_ZoneDelegate],
      _invokeTaskCurrZone: [Circular *1],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [_ZoneDelegate],
      _cancelTaskCurrZone: [Circular *1],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [_ZoneDelegate],
      _hasTaskDlgtOwner: [Circular *2],
      _hasTaskCurrZone: [Circular *1]
    }
  },
  task: ZoneTask {
    _zone: <ref *1> Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [_ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: [RuntimeError]
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function (anonymous)],
    invoke: [Function (anonymous)]
  }
}
```

**Comment by zawasp** [comment]
LE. This also happens with other Nitro presets, e.g. `azure`.

**Comment by luishcastroc** [comment]
same if you create a new app from scratch and just run it @brandonroberts 

```shell
ERROR RuntimeError: NG04002: Cannot match any routes. URL Segment: 'favicon.ico'
    at Recognizer.noMatchError (/Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/@angular+router@18.0.2_@angular+common@18.0.2_@angular+core@18.0.2_@angular+platform-browser@18.0.2_rxjs@7.5.7/node_modules/@angular/router/fesm2022/router.mjs:3838:16)
    at eval (/Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/@angular+router@18.0.2_@angular+common@18.0.2_@angular+core@18.0.2_@angular+platform-browser@18.0.2_rxjs@7.5.7/node_modules/@angular/router/fesm2022/router.mjs:3868:28)
    at /Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51
    at OperatorSubscriber._this._error (/Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
    at Subscriber.error (/Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (/Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (/Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/Users/luiscastrocabrera/Projects/resume-maker/node_modules/.pnpm/rxjs@7.5.7/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30) {
  code: 4002
}
```
