### ISSUE TITLE
[astro-angular] Beta 0.2.0-beta.11 published without content

### ISSUE THREAD

**Issue by glutengo** [analogjs/analog#417]
### Please provide the environment you discovered this bug in.

astro 2.4.1
astro-angular 0.2.0-beta.11

### Which area/package is the issue in?

astro-angular

### Description

The npm package of the 0.2.0-beta.11 version only has the readme and the package.json file in it:
https://www.npmjs.com/package/@analogjs/astro-angular/v/0.2.0-beta.11?activeTab=code
 In contrast to the previous versions such as 0.2.0-beta.10, there is no src folder. The package.json still points to `"./src/index.js"` in the `main entry`, so I suppose there should be a src directory. Currently, when installing it via `astro add @analogjs/astro-angular` and running `astro dev` there is an error because the `main` entry cannot be found.
Can you please publish a new version which has the correct contents again? Thank you and thank you for your amazing work! ❤️

For the meantime: Is there any way that I can install a previous version? `astro add @analogjs/astro-angular@0.2.0-beta.10` did not work.

### Please provide the exception or error you saw

```true
01:20:21 PM [astro] Unable to load /Users/<my_name>/projects/techtalk/fhir-on-astro/astro.config.mjs

 error   Failed to resolve entry for package "@analogjs/astro-angular". The package may have incorrect main/module/exports specified in its package.json.
  File:
    /Users/<my_name>/projects/techtalk/fhir-on-astro/astro.config.mjs
  Stacktrace:
Error: Failed to resolve entry for package "@analogjs/astro-angular". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///Users/<my_name>/projects/techtalk/fhir-on-astro/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:23382:11)
    at resolvePackageEntry (file:///Users/<my_name>/projects/techtalk/fhir-on-astro/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:23379:5)
    at tryNodeResolve (file:///Users/<my_name>/projects/techtalk/fhir-on-astro/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:23113:20)
    at Context.resolveId (file:///Users/<my_name>/projects/techtalk/fhir-on-astro/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:22874:28)
    at Object.resolveId (file:///Users/<my_name>/projects/techtalk/fhir-on-astro/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:42847:46)
    at async TransformContext.resolve (file:///Users/<my_name>/projects/techtalk/fhir-on-astro/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:42575:23)
    at async normalizeUrl (file:///Users/<my_name>/projects/techtalk/fhir-on-astro/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:40500:34)
    at async file:///Users/<my_name>/projects/techtalk/fhir-on-astro/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:40651:47
    at async Promise.all (index 1)
    at async TransformContext.transform (file:///Users/<my_name>/projects/techtalk/fhir-on-astro/node_modules/.pnpm/vite@4.3.8_@types+node@20.2.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:40577:13)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by glutengo** [comment]
> Thanks @glutengo. Must have been a bad build. I don't think `astro add` lets you specify a package version
> 
> Fixed in `0.2.0-beta.12`

perfect, thank you! I can confirm it works again
