### ISSUE TITLE
Create a new Nx project causes an error while serving.

### ISSUE THREAD

**Issue by luishcastroc** [analogjs/analog#476]
### Please provide the environment you discovered this bug in.

latest

### Which area/package is the issue in?

Don't know / other

### Description

When creating a new NX workspace with the Analog preset I get an error when trying to serve the project out of the box.

steps are the following:

- Create a new Nx Workspace using this command `npx create-nx-workspace@latest --preset=@analogjs/platform` using the name analog-test (for this example) and setting everything on default.
- use `nx serve analog-test` to serve the development server.

### Please provide the exception or error you saw

```true
failed to load config from /Users/luiscastrocabrera/Projects/analog-test/analog-test/vite.config.ts
Error: Cannot find module '@angular-devkit/build-angular/src/tools/babel/webpack-loader'
Require stack:
- /Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/vite-plugin-angular/src/lib/utils/devkit.js
- /Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/vite-plugin-angular/src/lib/compiler-plugin.js
- /Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js
- /Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/vite-plugin-angular/src/index.js
- /Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/platform/src/lib/platform-plugin.js
- /Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/platform/src/index.js
- /Users/luiscastrocabrera/Projects/analog-test/analog-test/vite.config.ts
- /Users/luiscastrocabrera/Projects/analog-test/node_modules/vite/dist/node/chunks/dep-e8f070e8.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._resolveFilename (/Users/luiscastrocabrera/Projects/analog-test/node_modules/tsconfig-paths/lib/register.js:103:40)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/vite-plugin-angular/src/lib/utils/devkit.js:4:26)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at _require.extensions.<computed> [as .js] (file:///Users/luiscastrocabrera/Projects/analog-test/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:64527:17)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/vite-plugin-angular/src/lib/utils/devkit.js',
    '/Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/vite-plugin-angular/src/lib/compiler-plugin.js',
    '/Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/vite-plugin-angular/src/lib/angular-vite-plugin.js',
    '/Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/vite-plugin-angular/src/index.js',
    '/Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/platform/src/lib/platform-plugin.js',
    '/Users/luiscastrocabrera/Projects/analog-test/node_modules/@analogjs/platform/src/index.js',
    '/Users/luiscastrocabrera/Projects/analog-test/analog-test/vite.config.ts',
    '/Users/luiscastrocabrera/Projects/analog-test/node_modules/vite/dist/node/chunks/dep-e8f070e8.js'
  ]
}
```

### Other information

package.json

```json
{
  "name": "@analog-test/source",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {},
  "private": true,
  "dependencies": {
    "@analogjs/content": "0.2.0-beta.15",
    "@analogjs/platform": "0.2.0-beta.17",
    "@analogjs/router": "0.2.0-beta.15",
    "@angular/animations": "~15.2.0",
    "@angular/common": "~15.2.0",
    "@angular/compiler": "~15.2.0",
    "@angular/core": "~15.2.0",
    "@angular/forms": "~15.2.0",
    "@angular/platform-browser": "~15.2.0",
    "@angular/platform-browser-dynamic": "~15.2.0",
    "@angular/platform-server": "~16.0.0",
    "@angular/router": "~15.2.0",
    "front-matter": "^4.0.2",
    "marked": "^5.0.2",
    "prismjs": "^1.29.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~15.2.0",
    "@angular-devkit/core": "~15.2.0",
    "@angular-devkit/schematics": "~15.2.0",
    "@angular/cli": "~15.2.0",
    "@angular/compiler-cli": "~15.2.0",
    "@angular/language-service": "~15.2.0",
    "@nx/angular": "~16.0.0",
    "@nx/cypress": "16.0.3",
    "@nx/devkit": "~16.0.0",
    "@nx/js": "16.0.3",
    "@nx/vite": "^16.0.0",
    "@nx/workspace": "16.3.2",
    "@schematics/angular": "~15.2.0",
    "@types/node": "16.11.7",
    "autoprefixer": "^10.4.0",
    "cypress": "^12.2.0",
    "jsdom": "^20.0.0",
    "nx": "16.3.2",
    "nx-cloud": "latest",
    "postcss": "^8.4.5",
    "prettier": "^2.6.2",
    "tailwindcss": "^3.0.2",
    "typescript": "~5.0.2",
    "vite": "^4.0.3",
    "vite-tsconfig-paths": "^4.0.2",
    "vitest": "^0.31.0"
  }
}
```

node version: 18.2.1
platform: M1Pro Mac

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
This should be resolved with the latest release `0.2.0-beta.19`.

```sh
npx create-nx-workspace@latest analog-nx-workspace --preset @analogjs/platform@latest
```

Re-open the issue if that isn't the case

**Comment by luishcastroc** [comment]
> ```shell
> npx create-nx-workspace@latest analog-nx-workspace --preset @analogjs/platform@latest
> ```

seems to be serving now however I get a different error now:

An error occured while server rendering /index.html:

	Method Promise.prototype.then called on incompatible receiver [object Object]
TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]
    at ZoneAwarePromise.then (<anonymous>)
    at node:internal/per_context/primordials:440:35
    at new Promise (<anonymous>)
    at new SafePromise (node:internal/per_context/primordials:408:29)
    at node:internal/per_context/primordials:440:9
    at Array.map (<anonymous>)
    at arrayToSafePromiseIterable (node:internal/per_context/primordials:437:5)
    at node:internal/per_context/primordials:453:21
    at new Promise (<anonymous>)
    at primordials.SafePromiseAll (node:internal/per_context/primordials:452:3

not sure if that might be my env or something else.

**Comment by brandonroberts** [comment]
You should be on at least Node 18.13.0
