### ISSUE TITLE
Router error on new project startup with Node18

### ISSUE THREAD

**Issue by JeanMeche** [analogjs/analog#528]
### Please provide the environment you discovered this bug in.

See description. 

### Which area/package is the issue in?

create-analog

### Description

I created a new project using the getting started :  `npm create analog@latest`

When starting the project, the App in the browser is fine but the terminal is logging : 

```
ERROR Error: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: 'service-worker.js'
Error: NG04002: Cannot match any routes. URL Segment: 'service-worker.js'
    at Recognizer.noMatchError (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/@angular/router/fesm2022/router.mjs:3664:16)
    at eval (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/@angular/router/fesm2022/router.mjs:3679:28)
    at /Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51
    at OperatorSubscriber._this._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
    at Subscriber.error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at Subscriber.error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
    at Subscriber._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
    at resolvePromise (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/zone.js/bundles/zone-node.umd.js:1179:35)
    at resolvePromise (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/zone.js/bundles/zone-node.umd.js:1133:21)
    at /Users/kyro/Developer/web/angular-projects/analog-project/node_modules/zone.js/bundles/zone-node.umd.js:1246:21
    at _ZoneDelegate.invokeTask (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/zone.js/bundles/zone-node.umd.js:446:35)
    at AsyncStackTaggingZoneSpec.onInvokeTask (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/@angular/core/fesm2022/core.mjs:25968:28)
    at _ZoneDelegate.invokeTask (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/zone.js/bundles/zone-node.umd.js:445:64)
    at Object.onInvokeTask (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/@angular/core/fesm2022/core.mjs:26266:33)
    at _ZoneDelegate.invokeTask (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/zone.js/bundles/zone-node.umd.js:445:64)
    at Zone.runTask (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/zone.js/bundles/zone-node.umd.js:211:51)
    at drainMicroTaskQueue (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/zone.js/bundles/zone-node.umd.js:635:39) {
  rejection: RuntimeError: NG04002: Cannot match any routes. URL Segment: 'service-worker.js'
      at Recognizer.noMatchError (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/@angular/router/fesm2022/router.mjs:3664:16)
      at eval (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/@angular/router/fesm2022/router.mjs:3679:28)
      at /Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51
      at OperatorSubscriber._this._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
      at Subscriber.error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
      at Subscriber.error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
      at Subscriber.error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
      at Subscriber._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30) {
    code: 4002
  },
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: RuntimeError: NG04002: Cannot match any routes. URL Segment: 'service-worker.js'
        at Recognizer.noMatchError (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/@angular/router/fesm2022/router.mjs:3664:16)
        at eval (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/@angular/router/fesm2022/router.mjs:3679:28)
        at /Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/operators/catchError.js:13:51
        at OperatorSubscriber._this._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:43:21)
        at Subscriber.error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
        at Subscriber._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
        at Subscriber.error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
        at Subscriber._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30)
        at Subscriber.error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:60:18)
        at Subscriber._error (/Users/kyro/Developer/web/angular-projects/analog-project/node_modules/rxjs/dist/cjs/internal/Subscriber.js:84:30) {
      code: 4002
    }
  },
  zone: <ref *1> Zone {
    _parent: Zone {
      _parent: [Zone],
      _name: 'asyncStackTagging for Angular',
      _properties: {},
      _zoneDelegate: [_ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: <ref *2> _ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular *1],
      _parentDelegate: [_ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [_ZoneDelegate],
      _invokeCurrZone: [Circular *1],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [_ZoneDelegate],
      _handleErrorCurrZone: [Circular *1],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [_ZoneDelegate],
      _scheduleTaskCurrZone: [Circular *1],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [_ZoneDelegate],
      _invokeTaskCurrZone: [Circular *1],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [_ZoneDelegate],
      _cancelTaskCurrZone: [Circular *1],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [_ZoneDelegate],
      _hasTaskDlgtOwner: [Circular *2],
      _hasTaskCurrZone: [Circular *1]
    }
  },
  task: ZoneTask {
    _zone: <ref *1> Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [_ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: [RuntimeError]
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function (anonymous)],
    invoke: [Function (anonymous)],
    consoleTask: null
  }
}
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
Was there some other app running on localhost in your browser that refreshed and requested the service worker?

We don't load any such files out of the box

**Comment by JeanMeche** [comment]
I've cleaned the cache, the issue doesn't occure anymore. I'll close it, thanks Brandon !
