### ISSUE TITLE
astro-angular: "client:load" throws `NG0203: inject()` in combination with external library

### ISSUE THREAD

**Issue by marcjulian** [analogjs/analog#537]
### Please provide the environment you discovered this bug in.

Reproduction repository

https://github.com/marcjulian/astro-analog-inject

### Which area/package is the issue in?

astro-angular

### Description

When using astro with "@analogjs/astro-angular", `client:load` and a directive from an external library the error below is thrown.

We have a library which expose a similar [LetDirective](https://github.com/marcjulian/astro-analog-inject/blob/main/src/components/let.directive.ts) as used in the reproduction repository. Weird thing is when the `LetDirective` is imported from the external library the error is thrown as below. When the `LetDirective` is copied into the project it works without any error and with `client:load` for the angular component.

As an example, I tried to use `RxLet` from [rx-angular](https://www.rx-angular.io/docs/template/api/rx-let-directive) and it behaves the same as with our library.

Do we need an additional configuration to support external libraries to work properly with astro-angular?

### Please provide the exception or error you saw

```true
ERROR RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:644:15)
    at ɵɵinject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:655:61)
    at inject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:738:12)
    at <instance_members_initializer> (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:52:24)
    at new RxLet (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:50:1)
    at NodeInjectorFactory.RxLet_Factory [as factory] (ng:///RxLet/ɵfac.js:5:10)
    at getNodeInjectable (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:4662:44)
    at instantiateAllDirectives (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11590:27)
    at createDirectivesInstances (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11006:5)
    at Module.ɵɵtemplate (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:15126:9) {
  code: -203
}
ERROR Error: Uncaught (in promise): Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:644:15)
    at ɵɵinject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:655:61)
    at inject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:738:12)
    at <instance_members_initializer> (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:52:24)
    at new RxLet (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:50:1)
    at NodeInjectorFactory.RxLet_Factory [as factory] (ng:///RxLet/ɵfac.js:5:10)
    at getNodeInjectable (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:4662:44)
    at instantiateAllDirectives (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11590:27)
    at createDirectivesInstances (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11006:5)
    at Module.ɵɵtemplate (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:15126:9)
    at resolvePromise (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/zone.js@0.13.1/node_modules/zone.js/bundles/zone-node.umd.js:1179:35)
    at /Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/zone.js@0.13.1/node_modules/zone.js/bundles/zone-node.umd.js:1250:21
    at _ZoneDelegate.invokeTask (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/zone.js@0.13.1/node_modules/zone.js/bundles/zone-node.umd.js:446:35)
    at AsyncStackTaggingZoneSpec.onInvokeTask (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:25968:28)
    at _ZoneDelegate.invokeTask (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/zone.js@0.13.1/node_modules/zone.js/bundles/zone-node.umd.js:445:64)
    at Object.onInvokeTask (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:26266:33)
    at _ZoneDelegate.invokeTask (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/zone.js@0.13.1/node_modules/zone.js/bundles/zone-node.umd.js:445:64)
    at Zone.runTask (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/zone.js@0.13.1/node_modules/zone.js/bundles/zone-node.umd.js:211:51)
    at drainMicroTaskQueue (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/zone.js@0.13.1/node_modules/zone.js/bundles/zone-node.umd.js:635:39) {
  rejection: RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
      at injectInjectorOnly (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:644:15)
      at ɵɵinject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:655:61)
      at inject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:738:12)
      at <instance_members_initializer> (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:52:24)
      at new RxLet (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:50:1)
      at NodeInjectorFactory.RxLet_Factory [as factory] (ng:///RxLet/ɵfac.js:5:10)
      at getNodeInjectable (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:4662:44)
      at instantiateAllDirectives (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11590:27)
      at createDirectivesInstances (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11006:5)
      at Module.ɵɵtemplate (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:15126:9) {
    code: -203
  },
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
        at injectInjectorOnly (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:644:15)
        at ɵɵinject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:655:61)
        at inject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:738:12)
        at <instance_members_initializer> (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:52:24)
        at new RxLet (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:50:1)
        at NodeInjectorFactory.RxLet_Factory [as factory] (ng:///RxLet/ɵfac.js:5:10)
        at getNodeInjectable (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:4662:44)
        at instantiateAllDirectives (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11590:27)
        at createDirectivesInstances (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11006:5)
        at Module.ɵɵtemplate (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:15126:9) {
      code: -203
    }
  },
  zone: <ref *1> Zone {
    _parent: Zone {
      _parent: [Zone],
      _name: 'asyncStackTagging for Angular',
      _properties: {},
      _zoneDelegate: [_ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true },
    _zoneDelegate: <ref *2> _ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular *1],
      _parentDelegate: [_ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [_ZoneDelegate],
      _invokeCurrZone: [Circular *1],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [_ZoneDelegate],
      _handleErrorCurrZone: [Circular *1],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [_ZoneDelegate],
      _scheduleTaskCurrZone: [Circular *1],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [_ZoneDelegate],
      _invokeTaskCurrZone: [Circular *1],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [_ZoneDelegate],
      _cancelTaskCurrZone: [Circular *1],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [_ZoneDelegate],
      _hasTaskDlgtOwner: [Circular *2],
      _hasTaskCurrZone: [Circular *1]
    }
  },
  task: ZoneTask {
    _zone: <ref *1> Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [_ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: [RuntimeError]
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function (anonymous)],
    invoke: [Function (anonymous)],
    consoleTask: null
  }
}
Unhandled Promise rejection: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203 ; Zone: <root> ; Task: Promise.then ; Value: RuntimeError: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:644:15)
    at ɵɵinject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:655:61)
    at inject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:738:12)
    at <instance_members_initializer> (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:52:24)
    at new RxLet (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:50:1)
    at NodeInjectorFactory.RxLet_Factory [as factory] (ng:///RxLet/ɵfac.js:5:10)
    at getNodeInjectable (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:4662:44)
    at instantiateAllDirectives (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11590:27)
    at createDirectivesInstances (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11006:5)
    at Module.ɵɵtemplate (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:15126:9) {
  code: -203
} Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:644:15)
    at ɵɵinject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:655:61)
    at inject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:738:12)
    at <instance_members_initializer> (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:52:24)
    at new RxLet (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:50:1)
    at NodeInjectorFactory.RxLet_Factory [as factory] (ng:///RxLet/ɵfac.js:5:10)
    at getNodeInjectable (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:4662:44)
    at instantiateAllDirectives (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11590:27)
    at createDirectivesInstances (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:11006:5)
    at Module.ɵɵtemplate (/Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:15126:9)
 error   NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
  File:
    /Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:644:15
  Code:
    643 |     if (_currentInjector === undefined) {
    > 644 |         throw new RuntimeError(-203 /* RuntimeErrorCode.MISSING_INJECTION_CONTEXT */, ngDevMode &&
          |               ^
      645 |             `inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with \`runInInjectionContext\`.`);
      646 |     }
      647 |     else if (_currentInjector === null) {
  Stacktrace:
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:644:15)
    at ɵɵinject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:655:61)
    at inject (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@angular+core@16.1.4_rxjs@7.8.1_zone.js@0.13.1/node_modules/@angular/core/fesm2022/core.mjs:738:12)
    at <instance_members_initializer> (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:52:24)
    at new RxLet (file:///Users/m/Dev/wip/astro-analog-inject/node_modules/.pnpm/@rx-angular+template@16.0.1_@angular-devkit+core@16.1.4_@angular-devkit+schematics@16.1.4_@an_7pphcyfrbrlrlf32d6ab2nyjjq/node_modules/@rx-angular/template/fesm2022/template-let.mjs:50:1)
    at NodeInjectorFactory.RxLet_Factory [as factory] (ng:///RxLet/ɵfac.js:5:10)
    at getNodeInjectable (/Users/m/Dev/wip/astro-analog-inject/node_modules/packages/core/src/util/property.ts:4658:44)
    at instantiateAllDirectives (/Users/m/Dev/wip/astro-analog-inject/node_modules/packages/core/src/util/property.ts:11586:27)
    at createDirectivesInstances (/Users/m/Dev/wip/astro-analog-inject/node_modules/packages/core/src/util/property.ts:11002:5)
    at Module.ɵɵtemplate (/Users/m/Dev/wip/astro-analog-inject/node_modules/packages/core/src/util/property.ts:15122:9)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This can be resolved by telling Vite to transform the external packages during SSR. It does not do this by default

https://analogjs.org/docs/features/server/server-side-rendering#transforming-packages-for-ssr-compatibility
https://analogjs.org/docs/packages/astro-angular/overview#configure-vite-angular-plugin

In the case of your usage in Astro:

```js
import { defineConfig } from "astro/config";

import angular from "@analogjs/astro-angular";

// https://astro.build/config
export default defineConfig({
  integrations: [angular()],
  vite: {
    ssr: {
      noExternal: ['@rx-angular/**']
    }
  }
});
```

**Comment by marcjulian** [comment]
Thanks for the quick feedback! It works in my reproduction repository and will try the configuration in another project as well. Do you think this should be added to the astro-angular docs? I could add a PR for it.

**Comment by brandonroberts** [comment]
Yes, that would be great, thanks.
