### ISSUE TITLE
Error running project after creating with latest Analog installer: Failed to resolve import index.page.ts

### ISSUE THREAD

**Issue by seanbh** [analogjs/analog#608]
### Please provide the environment you discovered this bug in.

Windows 11 machine using a command prompt and node 18.13.0, npm  9.8.1.

### Which area/package is the issue in?

create-analog

### Description

Followed the getting started instructions for npm and selected the Angular v16 template.  I get an error when running the project.

### Please provide the exception or error you saw

```true
[plugin:vite:import-analysis] Failed to resolve import "../../../../../../../../c:/code/demo/angular-analog/src/app/pages/index.page.ts" from "node_modules\@analogjs\router\fesm2022\analogjs-router.mjs?v=875b5aa3". Does the file exist?
../../../../packages/router/src/lib/routes.ts:11:44
143|  
144|  /// <reference types="vite/client" />
145|  const FILES = /* #__PURE__ */ Object.assign({"/src/app/pages/index.page.ts": () => import("../../../../../../../../c:/code/demo/angular-analog/src/app/pages/index.page.ts")
   |                                                                                            ^
146|  
147|
    at formatError (file:///c:/code/demo/angular-analog/node_modules/vite/dist/node/chunks/dep-df561101.js:43993:46)
    at TransformContext.error (file:///c:/code/demo/angular-analog/node_modules/vite/dist/node/chunks/dep-df561101.js:43989:19)
    at normalizeUrl (file:///c:/code/demo/angular-analog/node_modules/vite/dist/node/chunks/dep-df561101.js:41801:33)
    at async file:///c:/code/demo/angular-analog/node_modules/vite/dist/node/chunks/dep-df561101.js:41945:47
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by seanbh** [comment]
I tried using PowerShell instead and I don't get an error.

**Comment by brandonroberts** [comment]
Ok. PowerShell or a WSL environment is recommended.
