### ISSUE TITLE
AnalogJS + Astro: "NullInjectorError: No provider for HttpClient!"

### ISSUE THREAD

**Issue by rujorgensen** [analogjs/analog#655]
### Please provide the environment you discovered this bug in.

**Repo** (bug/unconfirmed/no-provider-for-httpclient branch)
https://github.com/rujorgensen/astro-3-analog-nx/tree/bug/unconfirmed/no-provider-for-httpclient

### Which area/package is the issue in?

astro-angular

### Description

I was trying out the [Adding Component Providers-step](https://analogjs.org/docs/packages/astro-angular/overview#adding-component-providers), but when serving (`nx run astro-v3:serve`), I get an injector-error ("NullInjectorError: No provider for HttpClient!")

![image](https://github.com/analogjs/analog/assets/6797319/4db63fe7-0a20-4b89-af8e-33e26af811dd)

I copied the component directly from the guide:
```TypeScript
import { Component, type OnInit, inject } from '@angular/core';
import { NgFor } from '@angular/common';
import { provideHttpClient, HttpClient } from '@angular/common/http';

interface Todo {
  id: number;
  title: string;
  completed: boolean;
}

@Component({
  selector: 'app-todos',
  standalone: true,
  imports: [NgFor],
  template: `
    <h2>Todos</h2>

    <ul>
      <li *ngFor="let todo of todos">
        {{ todo.title }}
      </li>
    </ul>
  `,
})
export class TodosComponent implements OnInit {
  static clientProviders = [provideHttpClient()];
  static renderProviders = [];

  http = inject(HttpClient);
  todos: Todo[] = [];

  ngOnInit() {
    this.http
      .get<Todo[]>('https://jsonplaceholder.typicode.com/todos')
      .subscribe((todos) => (this.todos = todos));
  }
}
```

... and added it to index.astro:
```TypeScript
---
import {TodosComponent } from '../components/todos/todos.component';

import { HelloComponent } from '../../../../../libs/frontend/ui/src/lib/hello/hello.component';

const helpText = "Helping binding";
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>Astro</title>
	</head>
	<body>
		<TodosComponent client:visible/>		
	</body>
</html>

```

### Please provide the exception or error you saw

```true
error   R3InjectorError(Environment Injector)[HttpClient -> HttpClient]: 
    NullInjectorError: No provider for HttpClient!
  File:
    C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:8853:27
  Stacktrace:
NullInjectorError: R3InjectorError(Environment Injector)[HttpClient -> HttpClient]: 
  NullInjectorError: No provider for HttpClient!
    at NullInjector.get (C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:8853:27)
    at R3Injector.get (C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:9292:33)
    at R3Injector.get (C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:9292:33)
    at ChainedInjector.get (C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:13949:36)
    at lookupTokenUsingModuleInjector (C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:4484:39)
    at getOrCreateInjectable (C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:4532:12)
    at ɵɵdirectiveInject (C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:11732:19)
    at ɵɵinject (C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:744:61)
    at Module.inject (C:\Users\rj\Documents\workspace\astro-ng-nx\node_modules\packages\core\src\util\property.ts:828:12)
    at new TodosComponent (C:\Users\rj\Documents\workspace\astro-ng-nx\apps\frontend\astro\src\components\todos\todos.component.ts:25:8)
```

### Other information

The repo is a simple Astro + AnalogJS only **NX monorepo**, although in the example here, the `TodosComponent` is placed alongside the Astro app for simplicity. I'm using **Astro v. 3.0.10**.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by Tenessy** [comment]
Hello @rujorgensen , your implementation seem wrong. You need to use the two statics arrays clientProviders and renderProviders. Add the clientProviders in your renderProviders like this `static renderProviders = [TodosComponent.clientProviders];`. To finish remove `client:visible` to your TodosComponent. It's work for me ;)

**Comment by rujorgensen** [comment]
@Tenessy thanks a lot, I really appreciate your input 🙂!

For future reference, I can confirm that this works for me too:
```TypeScript
import { Component, type OnInit, inject } from '@angular/core';
import { NgFor } from '@angular/common';
import { provideHttpClient, HttpClient } from '@angular/common/http';

interface Todo {
  id: number;
  title: string;
  completed: boolean;
}

@Component({
  selector: 'app-todos',
  standalone: true,
  imports: [NgFor],
  template: `
    <h2>Todos</h2>

    <ul>
      <li *ngFor="let todo of todos">
        {{ todo.title }}
      </li>
    </ul>
  `,
})
export class TodosComponent implements OnInit {
  static clientProviders = [provideHttpClient()];
  // ⚠️ I added this line ⬇️
  static renderProviders = [TodosComponent.clientProviders];
  // ⚠️ I added this line ⬆️

  http = inject(HttpClient);
  todos: Todo[] = [];

  ngOnInit() {
    this.http
      .get<Todo[]>('https://jsonplaceholder.typicode.com/todos')
      .subscribe((todos) => (this.todos = todos));
  }
}
```
