### ISSUE TITLE
[error] ERROR Error: Uncaught (in promise): ReferenceError: document is not defined

### ISSUE THREAD

**Issue by benruwel** [analogjs/analog#694]
### Please provide the environment you discovered this bug in.

Darwin Generic-MacBook-Air.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 arm64

### Which area/package is the issue in?

vite-plugin-angular

### Description

$ npx create-nx-workspace@latest --preset=@analogjs/platform
$ cd analog-workspace
$ npm install
$ nx serve analog-project

### Please provide the exception or error you saw

```true
$ nx serve projectName --port=4400

> nx run projectName:serve:development --port=4400



The server endpoints are accessible under the "/api" path.
  ➜  Local:   http://localhost:4400/
  ➜  Network: use --host to expose
Angular is running in development mode.
2:20:17 PM [vite] Error when evaluating SSR module /@fs/Users/projectName/node_modules/.pnpm/primeng@16.0.0-rc.2_@angular+common@16.2.7_@angular+core@16.2.7_@angular+forms@16.2.7_rxjs@7.8.1_zone.js@0.13.3/node_modules/primeng/fesm2022/primeng-editor.mjs: failed to import "quill"
|- ReferenceError: document is not defined
    at Object.<anonymous> (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:7661:12)
    at __webpack_require__ (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:1030:1)
    at __webpack_require__ (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:5655:14)
    at __webpack_require__ (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:10045:13)
    at __webpack_require__ (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
    at Object.<anonymous> (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:11557:18)
    at __webpack_require__ (/Users/projectName/node_modules/.pnpm/quill@1.3.7/node_modules/quill/dist/quill.js:36:30)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This is not a bug in Analog. If a library you use doesn't support SSR environments, you need to disable it for SSR and enable it in the browser.

Vite has a flag for this: `import.meta.env.SSR`

Angular also has APIs for this: `https://angular.io/api/common/isPlatformBrowser`
