### ISSUE TITLE
npm run start fails

### ISSUE THREAD

**Issue by fireflysemantics** [analogjs/analog#698]
### Please provide the environment you discovered this bug in.

When attempting to run `npm run start` it fails 

### Which area/package is the issue in?

platform

### Description

Running `npm run start` produces this error:

```
Node.js version v19.8.1 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
An unhandled exception occurred: Cannot read properties of undefined (reading 'executor')
See "/private/var/folders/m9/rwt3nk256b91bwq770bpkmhw0000gn/T/ng-thZIVp/angular-errors.log" for further details.
oleersoy@Oles-MacBook-Pro analog-project % cat /private/var/folders/m9/rwt3nk256b91bwq770bpkmhw0000gn/T/ng-thZIVp/angular-errors.log
[error] TypeError: Cannot read properties of undefined (reading 'executor')
    at readTargetOptions (/Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/devkit/src/executors/read-target-options.js:24:60)
    at getNxTargetOptions (/Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/vite/src/utils/options-utils.js:137:42)
    at viteDevServerExecutor (/Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/vite/src/executors/dev-server/dev-server.impl.js:24:69)
    at viteDevServerExecutor.next (<anonymous>)
    at recurse (/Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/devkit/src/utils/convert-nx-executor.js:61:26)
    at /Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/devkit/src/utils/convert-nx-executor.js:78:17
```

### Please provide the exception or error you saw

```true
Node.js version v19.8.1 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
An unhandled exception occurred: Cannot read properties of undefined (reading 'executor')
See "/private/var/folders/m9/rwt3nk256b91bwq770bpkmhw0000gn/T/ng-thZIVp/angular-errors.log" for further details.
oleersoy@Oles-MacBook-Pro analog-project % cat /private/var/folders/m9/rwt3nk256b91bwq770bpkmhw0000gn/T/ng-thZIVp/angular-errors.log
[error] TypeError: Cannot read properties of undefined (reading 'executor')
    at readTargetOptions (/Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/devkit/src/executors/read-target-options.js:24:60)
    at getNxTargetOptions (/Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/vite/src/utils/options-utils.js:137:42)
    at viteDevServerExecutor (/Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/vite/src/executors/dev-server/dev-server.impl.js:24:69)
    at viteDevServerExecutor.next (<anonymous>)
    at recurse (/Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/devkit/src/utils/convert-nx-executor.js:61:26)
    at /Users/oleersoy/Temp/analog-workspace/analog-project/node_modules/@nx/devkit/src/utils/convert-nx-executor.js:78:17
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by brandonroberts** [comment]
A known issue with Nx

https://github.com/analogjs/analog/issues/667#issuecomment-1743046101
