### ISSUE TITLE
Newly generated app can not be served: "Could not find vite config at provided path"

### ISSUE THREAD

**Issue by PowerSupply** [analogjs/analog#699]
### Please provide the environment you discovered this bug in.

Just followed the steps in the docs for creating an app in an exising NX workspace. Fails on trying to serve the newly generated app.

### Which area/package is the issue in?

create-analog

### Description

Error when running

npx nx serve analog-app

after creating with:

npx nx g @analogjs/platform:app analog-app

### Please provide the exception or error you saw

```true
>  NX   Could not find vite config at provided path "/spear/vite.config.ts".

Error: Could not find vite config at provided path "/spear/vite.config.ts".
    at normalizeViteConfigFilePath (/Users/myuser/Documents/Dev/gaia/node_modules/@nx/vite/src/utils/options-utils.js:44:19)
    at getViteSharedConfig (/Users/myuser/Documents/Dev/gaia/node_modules/@nx/vite/src/utils/options-utils.js:69:21)
    at viteDevServerExecutor (/Users/myuser/Documents/Dev/gaia/node_modules/@nx/vite/src/executors/dev-server/dev-server.impl.js:29:87)
    at viteDevServerExecutor.next (<anonymous>)
    at getLastValueFromAsyncIterableIterator (/Users/myuser/Documents/Dev/gaia/node_modules/nx/src/utils/async-iterator.js:13:27)
    at iteratorToProcessStatusCode (/Users/myuser/Documents/Dev/gaia/node_modules/nx/src/command-line/run/run.js:41:94)
    at /Users/myuser/Documents/Dev/gaia/node_modules/nx/src/command-line/run/run.js:154:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/Users/myuser/Documents/Dev/gaia/node_modules/nx/src/utils/params.js:9:16)
    at async process.<anonymous> (/Users/myuser/Documents/Dev/gaia/node_modules/nx/bin/run-executor.js:59:28)
```

### Other information

I just followed the steps in the Docs:
https://analogjs.org/docs/integrations/nx#adding-to-an-existing-nx-workspace

My Nx version is 16.8.1

Newly generated project.json
```
{
    "name": "spear",
    "$schema": "../node_modules/nx/schemas/project-schema.json",
    "projectType": "application",
    "sourceRoot": "/spear/src",
    "targets": {
        "build": {
            "executor": "@nx/vite:build",
            "outputs": [
                "{options.outputPath}",
                "{workspaceRoot}/dist//spear/.nitro",
                "{workspaceRoot}/dist//spear/ssr",
                "{workspaceRoot}/dist//spear/analog"
            ],
            "options": {
                "main": "/spear/src/main.ts",
                "configFile": "/spear/vite.config.ts",
                "outputPath": "dist//spear/client"
            },
            "defaultConfiguration": "production",
            "configurations": {
                "development": {
                    "mode": "development"
                },
                "production": {
                    "sourcemap": false,
                    "mode": "production"
                }
            }
        },
        "serve": {
            "executor": "@nx/vite:dev-server",
            "defaultConfiguration": "development",
            "options": {
                "buildTarget": "spear:build",
                "port": 4200
            },
            "configurations": {
                "development": {
                    "buildTarget": "spear:build:development",
                    "hmr": true
                },
                "production": {
                    "buildTarget": "spear:build:production"
                }
            }
        },
        "extract-i18n": {
            "executor": "@angular-devkit/build-angular:extract-i18n",
            "options": {
                "browserTarget": "spear:build"
            }
        },
        "test": {
            "executor": "@nx/vite:test",
            "outputs": ["{projectRoot}/coverage"]
        },
        "lint": {
            "executor": "@nx/linter:eslint",
            "outputs": ["{options.outputFile}"],
            "options": {
                "lintFilePatterns": ["/spear/**/*.{ts,html}"]
            }
        }
    },
    "tags": []
}
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by brandonroberts** [comment]
Interesting. Try changing the occurrences of `/spear` to spear in the `project.json`

**Comment by PowerSupply** [comment]
Tried that, no difference. Also there are paths with "//" which I don't think should be there. Didnt make a difference when I changed it.

**Comment by brandonroberts** [comment]
Ok, thanks.  Will take a look

**Comment by PowerSupply** [comment]
Any new insight? Or can I assist in any way?

**Comment by PowerSupply** [comment]
I just tested with Nx 17.0.2 and it is not resolved. Still same error.

**Comment by PowerSupply** [comment]
I think the problem is that the path is resolved from the very root of the disk and not the root of the Nx workspace

**Comment by PowerSupply** [comment]
this is options.configFile that gets passed into normalizeViteConfigFilePath:
```
{
  main: '/analog-app/src/main.ts',
  configFile: '/analog-app/vite.config.ts',
  outputPath: 'dist/analog-app/client',
  tsConfig: '/analog-app/tsconfig.app.json',
  mode: 'development',
  buildLibsFromSource: true,
  skipTypeCheck: false,
  fileReplacements: [],
  emptyOutDir: true,
  watch: false,
  buildTarget: 'analog-app:build:development',
  port: 4200,
  hmr: true
}
```

**Comment by PowerSupply** [comment]
It seems like the typing does not add upp since that `configFile` object is typed to be a `string`, see https://github.com/nrwl/nx/blob/f9fc3dd42bf202ae10b7e762800a3d0d6fd81243/packages/vite/src/utils/options-utils.ts#L27

**Comment by brandonroberts** [comment]
I tried with these options and it works correctly.

```
$npx create-nx-workspace@latest analog-nx-paths  
Need to install the following packages:
  create-nx-workspace@17.0.2
Ok to proceed? (y)
 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · integrated
✔ Enable distributed caching to make your CI faster · No

 >  NX   Creating your v17.0.2 workspace.

   To make sure the command works reliably in all environments, and that the preset is applied correctly,
   Nx will run "npm install" several times. Please wait.

✔ Installing dependencies with npm
✔ Successfully created the workspace: analog-nx-paths.

 ——————————————————————————————————————————————————————————————————————————————————


 >  NX   First time using Nx? Check out this interactive Nx tutorial.

   https://nx.dev/getting-started/tutorials/package-based-repo-tutorial

$cd analog-nx-paths
$npm i @analogjs/platform --save-dev
npm WARN deprecated @babel/plugin-proposal-unicode-property-regex@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated @wessberg/ts-evaluator@0.0.27: this package has been renamed to ts-evaluator. Please install ts-evaluator instead

added 639 packages, and audited 1013 packages in 42s

123 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$nx g @analogjs/platform:app analog-app

>  NX  Generating @analogjs/platform:app

✔ Add TailwindCSS for styling? (Y/n) · true
✔ Add tRPC for typesafe client/server interaction? (y/N) · false
Angular has not been installed yet. Creating an Angular application
Fetching @nx/angular...
Fetching prettier...
UPDATE package.json
UPDATE nx.json
CREATE tsconfig.base.json
CREATE .prettierrc
CREATE .prettierignore
UPDATE .vscode/extensions.json
UPDATE .gitignore
CREATE analog-app/project.json
CREATE analog-app/.eslintrc.json
CREATE analog-app/index.html
CREATE analog-app/src/app/app.component.spec.ts
CREATE analog-app/src/app/app.component.ts
CREATE analog-app/src/app/app.config.server.ts
CREATE analog-app/src/app/app.config.ts
CREATE analog-app/src/favicon.ico
CREATE analog-app/src/main.server.ts
CREATE analog-app/src/main.ts
CREATE analog-app/src/public/assets/.gitkeep
CREATE analog-app/src/public/assets/analog.svg
CREATE analog-app/src/server/routes/v1/hello.ts
CREATE analog-app/src/styles.css
CREATE analog-app/src/test-setup.ts
CREATE analog-app/src/vite-env.d.ts
CREATE analog-app/tsconfig.app.json
CREATE analog-app/tsconfig.editor.json
CREATE analog-app/tsconfig.json
CREATE analog-app/tsconfig.spec.json
CREATE analog-app/vite.config.ts
CREATE analog-app/tailwind.config.js
CREATE analog-app/postcss.config.js
CREATE analog-app/src/app/pages/(home).page.ts
CREATE analog-app/src/app/pages/analog-welcome.component.ts
CREATE .eslintrc.json
CREATE .eslintignore
```

What steps did you take?

**Comment by PowerSupply** [comment]
Yes, it works if you are [Creating a Standalone Nx project](https://analogjs.org/docs/integrations/nx#creating-a-standalone-nx-project)
, like you did. It does not work if you are [Adding to an existing Nx workspace](https://analogjs.org/docs/integrations/nx#adding-to-an-existing-nx-workspace), like I wrote I did in the description.

I made a diff of the project.json for the app created in the standalone Nx project and the one in my existing workspace. The differences are:
1. sourceRoute and targets.lint.options.lintFilePatterns[0] starts with "./analog-app/" vs "/analog-app/" (working vs non-working)
2. Paths in targets.build.outputs does not contain "//" in the in the working one (see project.json above for comparison)
3. Paths in targets.build.options does not lead with "/" in the working one.

After changing the paths, it works. So the bug is that the wrong paths are being generated when using the generator in an existing Nx workspace.

**Comment by brandonroberts** [comment]
Right. What I'm saying is generating a new workspace + using the generator should be the same as having an existing workspace + using the generator. 

I didn't create a standalone Nx project. I created a new empty workspace without the preset, installed the package and used the generator to generate the app.

There was a fix for Nx relevant to this here https://github.com/analogjs/analog/pull/617

You may want to check that you're installing the latest version using `@analogjs/platform@latest` and not an old cached version.
