### ISSUE TITLE
Analog StackBlitz example is broken

### ISSUE THREAD

**Issue by Pascalmh** [analogjs/analog#721]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/github/analogjs/analog/tree/main/packages/create-analog/template-angular-v16

### Which area/package is the issue in?

Don't know / other

### Description

When clicking on the "Use the Analog Stackblitz example to create a reproduction" link in the Issue-Template here on Github the `ng serve` command runs into an unhandled exception.

### Please provide the exception or error you saw

```true
~/projects/wmaiylypq.github
❯ npm install && npm run dev
// …
added 1801 packages in 8s

// …

> my-app@0.0.0 dev
> ng serve

An unhandled exception occurred: Package "@analogjs/platform" has no builders defined.
See "/tmp/ng-cDmamI/angular-errors.log" for further details.
```
```


### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by brandonroberts** [comment]
This will be resolved with the next release that includes the new executors.

**Comment by Pascalmh** [comment]
@brandonroberts I'm still getting an error - [Cannot load native addon
](https://developer.stackblitz.com/platform/webcontainers/troubleshooting-webcontainers#cannot-load-native-addon) - when StackBlitz tries to start (ng serve) the app:

```
> ng serve

An unhandled exception occurred: Cannot load native addon because loading addons is disabled: /home/projects/aoniwxjxw.github/node_modules/@nx/nx-linux-x64-musl/nx.linux-x64-musl.node
See "/tmp/ng-g8pWhN/angular-errors.log" for further details.
```

Here's the Content of the angular-errors.log file:

```
[error] Error: Cannot load native addon because loading addons is disabled: /home/projects/aoniwxjxw.github/node_modules/@nx/nx-linux-x64-musl/nx.linux-x64-musl.node
    at process.dlopen (https://aoniwxjxwgithub-ime3.w-credentialless.staticblitz.com/blitz.f76cc998.js:352:58832)
    at Module._extensions..node (https://aoniwxjxwgithub-ime3.w-credentialless.staticblitz.com/blitz.f76cc998.js:55:15948)
    at Module.load (https://aoniwxjxwgithub-ime3.w-credentialless.staticblitz.com/blitz.f76cc998.js:55:13469)
    at Module._load (https://aoniwxjxwgithub-ime3.w-credentialless.staticblitz.com/blitz.f76cc998.js:55:10541)
    at Module.require (https://aoniwxjxwgithub-ime3.w-credentialless.staticblitz.com/blitz.f76cc998.js:55:13787)
    at i (https://aoniwxjxwgithub-ime3.w-credentialless.staticblitz.com/blitz.f76cc998.js:98:2198)
    at _0x2f86ea (https://aoniwxjxwgithub-ime3.w-credentialless.staticblitz.com/blitz.f76cc998.js:352:203608)
    at Object.eval (file:///home/projects/aoniwxjxw.github/node_modules/nx/src/native/index.js:171:31)
    at Object.function (https://aoniwxjxwgithub-ime3.w-credentialless.staticblitz.com/blitz.f76cc998.js:352:204397)
    at Module._compile (https://aoniwxjxwgithub-ime3.w-credentialless.staticblitz.com/blitz.f76cc998.js:55:14883)
```

**Comment by brandonroberts** [comment]
It should be using `vite` in StackBlitz instead when using `https://analogjs.org/new`

**Comment by Pascalmh** [comment]
That works!

Looks like the Link in the Gitlab-Issue-Template needs updating then:

![stackblitz-link](https://github.com/analogjs/analog/assets/498197/81e29be4-d93c-4967-84a4-9a5df3f40fe5)
