### ISSUE TITLE
Compatibility of @astrojs/node with @analogjs/astro-angular

### ISSUE THREAD

**Issue by Antonytm** [analogjs/analog#748]
### Please provide the environment you discovered this bug in.

https://stackblitz.com/edit/withastro-astro-7sza4d?file=astro.config.mjs

Astro                    v3.5.1
Node                     v18.16.1
System                   Windows (x64)
Package Manager          npm
Output                   server
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap

### Which area/package is the issue in?

astro-angular

### Description

I want to use @analogjs/astro-angular together with @astro/node.

I follow instructions https://analogjs.org/docs/packages/astro-angular/overview
I follow instructions https://docs.astro.build/en/guides/integrations-guide/node/

Once I add 
```
  output: 'server',
  adapter: node({
    mode: 'standalone',
  }),
 ```
 
 It breaks all pages with error message:
 ```
 06:41:48 PM [config]  error   __vite_ssr_import_3__.node is not a function
  File:
    C:\source\demo20231103\evolved-eclipse\node_modules\vite\dist\node\chunks\dep-bb8a8339.js:56052:9
  Code:
    56051 |             `\n//# sourceURL=${mod.id}${sourceMapSuffix}`);
    > 56052 |         await initModule(context.global, ssrModule, ssrImportMeta, ssrImport, ssrDynamicImport, ssrExportAll);
            |         ^
      56053 |     }
      56054 |     catch (e) {
      56055 |         mod.ssrError = e;
  Stacktrace:
TypeError: __vite_ssr_import_3__.node is not a function
    at C:\source\demo20231103\evolved-eclipse\astro.config.mjs:14:12
    at async instantiateModule (file:///C:/source/demo20231103/evolved-eclipse/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)
 ```
instructions

### Please provide the exception or error you saw

```true
06:41:48 PM [config]  error   __vite_ssr_import_3__.node is not a function
  File:
    C:\source\demo20231103\evolved-eclipse\node_modules\vite\dist\node\chunks\dep-bb8a8339.js:56052:9
  Code:
    56051 |             `\n//# sourceURL=${mod.id}${sourceMapSuffix}`);
    > 56052 |         await initModule(context.global, ssrModule, ssrImportMeta, ssrImport, ssrDynamicImport, ssrExportAll);
            |         ^
      56053 |     }
      56054 |     catch (e) {
      56055 |         mod.ssrError = e;
  Stacktrace:
TypeError: __vite_ssr_import_3__.node is not a function
    at C:\source\demo20231103\evolved-eclipse\astro.config.mjs:14:12
    at async instantiateModule (file:///C:/source/demo20231103/evolved-eclipse/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)
 ```

or
```
dd `export const prerender = true;` to prerender this page.
 error   post.render is not a function
  File:
    /home/projects/withastro-astro-7sza4d/src/pages/blog/[...slug].astro:23:34
  Stacktrace:
TypeError: post.render is not a function
    at eval (/home/projects/withastro-astro-7sza4d/src/pages/blog/[...slug].astro:23:34)
    at [...slug] (/home/projects/withastro-astro-7sza4d/node_modules/astro/dist/runtime/server/astro-component.js:21:12)
    at callComponentAsTemplateResultOrResponse (file:///home/projects/withastro-astro-7sza4d/node_modules/astro/dist/runtime/server/render/astro/render.js:101:31)
    at Module.renderToReadableStream (file:///home/projects/withastro-astro-7sza4d/node_modules/astro/dist/runtime/server/render/astro/render.js:51:32)
    at Module.renderPage (file:///home/projects/withastro-astro-7sza4d/node_modules/astro/dist/runtime/server/render/page.js:44:35)
    at Module.renderPage (file:///home/projects/withastro-astro-7sza4d/node_modules/astro/dist/core/render/core.js:69:51)
    at #tryRenderRoute (file:///home/projects/withastro-astro-7sza4d/node_modules/astro/dist/core/pipeline.js:122:40)
    at DevPipeline.renderRoute (file:///home/projects/withastro-astro-7sza4d/node_modules/astro/dist/core/pipeline.js:67:46)
    at Module.handleRoute (file:///home/projects/withastro-astro-7sza4d/node_modules/astro/dist/vite-plugin-astro-server/route.js:234:33)
    at async run (file:///home/projects/withastro-astro-7sza4d/node_modules/astro/dist/vite-plugin-astro-server/request.js:70:14)
```
```


### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by Antonytm** [comment]
One important detail: the issue appears when you open some dynamic route page URLs.

**Comment by Antonytm** [comment]
The issue was solved. 

**Explanation, what was happened and how to fix it:**

When you follow the instructions to configure [@analogjs/astro-angular](https://analogjs.org/docs/packages/astro-angular/overview), there is requirement to add `tsconfig.app.json` with next configureation:

```
...
"include": ["src/**/*.ts", "src/**/*.tsx"]
...
```

In my case, I had dependencies outside of the project. (Some kind of monorepo).
`tsconfig.json`:
```
    "paths": {
      "@astro-sitecore-jss/astro-sitecore-jss": [
        "packages/astro-sitecore-jss/index.ts"
      ]
    }
 ```
` astro.config.mjs`:
```
  vite: {
    resolve: {
      alias: [
        {
          find: '@astro-sitecore-jss/astro-sitecore-jss',
          replacement: 'packages/astro-sitecore-jss',
        },
      ],
    },
```

That was done for convenient development of packages that could be used separately. 
And, these files were excluded from the final bundle.

**How to fix it:**
I updated `tsconfig.app.json` with:
```
"include": ["src/**/*.ts", "src/**/*.tsx", "../astro-sitecore-jss/**/*.ts", "../astro-sitecore-jss/**/*.tsx, ../astro-sitecore-jss/**/*.Astro"],
```
And everything started to work for me!
