### ISSUE TITLE
play is not a function

### ISSUE THREAD

**Issue by geommr** [analogjs/analog#813]
### Please provide the environment you discovered this bug in.

Analogjs v0.2.29

### Which area/package is the issue in?

Don't know / other

### Description

Relevant code snippet:
```html
<video playsinline autoplay muted loop #videoRef>
    <source src="vid.webm" type="video/webm">
</video>
```
```js
@ViewChild('videoRef', { static: true }) videoRef!: ElementRef;

ngAfterViewInit(): void {
    const media: HTMLVideoElement = this.videoRef.nativeElement;
    media.muted = true;
    media.play();
}
```

Is this an expected behavior, or am I missing something? It runs fine on a basic Angular app so I don't think its angular related.

### Please provide the exception or error you saw

```true
ERROR TypeError: media.play is not a function
    at HomeComponent.ngAfterViewInit (/.../src/app/pages/index.page.ts:18:15)
    at callHookInternal (/.../node_modules/@angular/core/fesm2022/core.mjs:3924:14)
    at callHook (/h.../node_modules/@angular/core/fesm2022/core.mjs:3951:13)
    at callHooks (/.../node_modules/@angular/core/fesm2022/core.mjs:3906:17)
    at executeInitAndCheckHooks (/.../node_modules/@angular/core/fesm2022/core.mjs:3856:9)
    at refreshView (/.../node_modules/@angular/core/fesm2022/core.mjs:13557:21)
    at detectChangesInView (/.../node_modules/@angular/core/fesm2022/core.mjs:13651:9)
    at detectChangesInEmbeddedViews (/.../node_modules/@angular/core/fesm2022/core.mjs:13594:13)
    at refreshView (/.../node_modules/@angular/core/fesm2022/core.mjs:13510:9)
    at detectChangesInView (/.../node_modules/@angular/core/fesm2022/core.mjs:13651:9)
```

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

**Comment by goetzrobin** [comment]
This is because you're accessing a browser API and AnalogJs does server side rendering where that does not exist. You can inject PLATFORM_ID and then use the isBrowser function from Angular to conditionally execute the play function only in the browser. Let me know if this helps

**Comment by geommr** [comment]
Of course I think of that after opening an issue, makes sense. Thanks for the quick reply!
