### ISSUE TITLE
[FEAT]: Add support for passing environment providers to Angular components used in Astro

### ISSUE THREAD

**Issue by brandonroberts** [analogjs/analog#97]
### Which scope/s are relevant/related to the feature request?

astro-angular

### Information

Currently, you can only use component-level providers, and do not have access to pass environment-level providers when rendering on the server or hydrating on the client.

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

**Comment by himyjan** [comment]
[@analogjs/astro-angular with @example/framework-multiple log tsx error test repo](https://github.com/himyjan/Astro/tree/%40analogjs/astro-angular)
```
 npm run dev

> @example/framework-multiple@0.0.1 dev
> astro dev

  🚀  astro  v1.4.2 started in 5666ms
  
  ┃ Local    http://127.0.0.1:3000/
  ┃ Network  use --host to expose
  
下午08:46:13 [astro] update /tsconfig.app.json
✘ [ERROR] [plugin angular-compiler] File is missing from the TypeScript compilation.

    src/components/ReactCounter.tsx:0:0:
      0 │ 
        ╵ ^

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.

✘ [ERROR] [plugin angular-compiler] File is missing from the TypeScript compilation.

    src/components/SolidCounter.tsx:0:0:
      0 │ 
        ╵ ^

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.

✘ [ERROR] [plugin angular-compiler] File is missing from the TypeScript compilation.

    src/components/PreactCounter.tsx:0:0:
      0 │ 
        ╵ ^

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.

Build failed with 1 error:
src/components/ReactCounter.tsx:0:0: ERROR: [plugin: angular-compiler] File is missing from the TypeScript compilation.
Sourcemap for "/Users/user/Desktop/Astro/node_modules/@analogjs/astro-angular/src/server.js" points to missing source files
Angular is running in development mode. Call enableProdMode() to enable production mode.
 error   Unable to render react.Counter because it is undefined!
  Did you forget to import the component or is it possible there is a typo?
Error: Unable to render react.Counter because it is undefined!
Did you forget to import the component or is it possible there is a typo?
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/render/component.js:68:11)
/node_modules/astro/dist/runtime/server/render/component.js:74
    throw new Error(
          ^

Error: Unable to render PreactCounter because it is undefined!
Did you forget to import the component or is it possible there is a typo?
    at Module.renderComponent (/node_modules/astro/dist/runtime/server/render/component.js:74:11)
```

**Comment by brandonroberts** [comment]
@himyjan this is not relevant to this issue.

The fix is to add the `.tsx` files to the includes array of the `tsconfig.app.json`
